### ISSUE TITLE
MVO Algorithms

### ISSUE THREAD

**Issue by LAR-UFSC** [ososinski/mvo#1]
Any one found the implementation of the MVO algorithm used on the paper "Ososinski, M., Labrosse, F. 2014. Multi-Viewpoint Visibility Coverage Estimation for 3D Environment Perception: Volumetric Representation as a Gateway to High Resolution Data. International Conference on Computer Vision Theory and Applications (VISAPP 2014), Lisbon, Portugal, 05/01/2014 - 08/01/2014. pp. 462-469. Cadair" ?

**Comment by ososinski** [comment]
Are you interested in the measurement implementation, any specific part of the algorithm or the whole processing chain?

The code is separated into several standalone modules ( initial viewpoint generation) local visibility estimate, global visibility estimate, and viewpoint reduction.

It was never released as it uses octomap for the data representation and GPL is not a very desirable  license. then again it should work with any volumetric representation supporting raycast.

I am happy to share the source code.

**Comment by LAR-UFSC** [comment]
Would be great if you can share the code.

I'm interested in the whole code, but if you can share just some parts, the ones which interest me most are the local visibility estimate and global visibility estimate (specially the first one).

About data representation for view planning is not usual use octomap, even I work with triangles mesh. But now I desire to try use octomap and for sure your code will help me a lot.

Thank you.

**Comment by ososinski** [comment]
Sorry it took me so long, I had to get it approved.

The code will require octomap to work and uses the binary tree file as input ( though you could load any file with octomap instead.

the viewpoints to consider are hardcoded as a vector, could be easily changed to be read from a config file.

The parts you were interested in are there. Though they are in research quality code,  that has not been optimised.

**Comment by LAR-UFSC** [comment]
Perfect, thanks.

I already use octomap with some others code I'm working now.
